mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          39626333376438616439653338333562396361396664643162333632373362613032383064366330
          6135396333373633343632656234336165326162303563340a383464393335356665373831633261
          64393333643466376136323561643132323035646133366466383261336539366238313338653132
          6466303961303661640a633566656238386365313032643934663537353230363134303563353664
          6532
